"""add combined_rating

Revision ID: 9064c5aeed15
Revises: fc603d790f41
Create Date: 2025-11-27 14:20:05.329942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9064c5aeed15'
down_revision: Union[str, Sequence[str], None] = 'fc603d790f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('combined_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'combined_rating')
    # ### end Alembic commands ###
