"""change movies

Revision ID: c0177ae058ee
Revises: a90be6cadd4e
Create Date: 2025-12-11 13:00:40.683278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0177ae058ee'
down_revision: Union[str, Sequence[str], None] = 'a90be6cadd4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('enriched_movies')

    # Обнуляем колонки
    op.execute("UPDATE movies SET persons = NULL, director = NULL")

    # Теперь безопасно меняем тип
    op.alter_column('movies', 'persons',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    type_=postgresql.ARRAY(sa.String()),
                    nullable=True,
                    postgresql_using="NULL::text[]")

    op.alter_column('movies', 'director',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    type_=sa.String(),
                    nullable=True,
                    postgresql_using="NULL::text")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'director',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('movies', 'persons',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('enriched_movies',
    sa.Column('kp_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title_ru_db', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title_en_db', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('year_release', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('movie_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('poster_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('genres', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('countries', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('director', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('persons', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kp_rating', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('imdb_rating', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('combined_rating', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('budget', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title_ru_csv', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('csv_category_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('csv_category_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('csv_category_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('csv_category_4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('csv_rating_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('csv_rating_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('csv_rating_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('kp_id', name=op.f('enriched_movies_pkey'))
    )
    # ### end Alembic commands ###
