"""add analytics models

Revision ID: c497c0bd4bcb
Revises: 7c8685625500
Create Date: 2025-12-17 11:42:16.467257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c497c0bd4bcb'
down_revision: Union[str, Sequence[str], None] = '7c8685625500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_logs_created_at'), 'error_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_error_logs_id'), 'error_logs', ['id'], unique=False)
    op.create_index(op.f('ix_error_logs_level'), 'error_logs', ['level'], unique=False)
    op.create_table('movie_view_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_view_logs_created_at'), 'movie_view_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_movie_view_logs_id'), 'movie_view_logs', ['id'], unique=False)
    op.create_index(op.f('ix_movie_view_logs_movie_id'), 'movie_view_logs', ['movie_id'], unique=False)
    op.create_table('page_view_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_view_logs_created_at'), 'page_view_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_page_view_logs_id'), 'page_view_logs', ['id'], unique=False)
    op.create_index(op.f('ix_page_view_logs_path'), 'page_view_logs', ['path'], unique=False)
    op.create_table('search_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('has_results', sa.Boolean(), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_logs_created_at'), 'search_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_logs_has_results'), 'search_logs', ['has_results'], unique=False)
    op.create_index(op.f('ix_search_logs_id'), 'search_logs', ['id'], unique=False)
    op.create_index(op.f('ix_search_logs_query'), 'search_logs', ['query'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_logs_query'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_id'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_has_results'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_created_at'), table_name='search_logs')
    op.drop_table('search_logs')
    op.drop_index(op.f('ix_page_view_logs_path'), table_name='page_view_logs')
    op.drop_index(op.f('ix_page_view_logs_id'), table_name='page_view_logs')
    op.drop_index(op.f('ix_page_view_logs_created_at'), table_name='page_view_logs')
    op.drop_table('page_view_logs')
    op.drop_index(op.f('ix_movie_view_logs_movie_id'), table_name='movie_view_logs')
    op.drop_index(op.f('ix_movie_view_logs_id'), table_name='movie_view_logs')
    op.drop_index(op.f('ix_movie_view_logs_created_at'), table_name='movie_view_logs')
    op.drop_table('movie_view_logs')
    op.drop_index(op.f('ix_error_logs_level'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_created_at'), table_name='error_logs')
    op.drop_table('error_logs')
    # ### end Alembic commands ###
